version: '3.7'
services:
  backend:
    build:
      context: backend
    ports:
      - "{{ cookiecutter.backend_port }}:{{ cookiecutter.backend_port }}"
    env_file: .env
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    expose:
     - 11434/tcp
    ports:
     - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]

volumes:
  ollama:

